### PR TITLE
Feature/perltidy code

### PR DESCRIPTION
**Pull request by bebehei**
add perltidyrc-file to make code tidier. The actual tidying will be commited later.

### CODE REVIEW

**Comment by bebehei** [comment]
How the tidied file will look like:
    $ perltidy rsnapshot-program.pl

**Comment by bebehei** [comment]
If travis finishes, I would merge this. Has got anyone an objection with that?

**Comment by sam-at-github** [comment]
None here. Finally, whoopy!

**Comment by bebehei** [comment]
Finally, travis also finished:

https://travis-ci.org/rsnapshot/rsnapshot/builds/64574569

**Comment by bebehei** [comment]
Before I'll merge, I have to add a section in CONTRIBUTING.md about new Pullrequests. The user should be advised to run perltidy before committing.

**Pull request merged**
