### PR TITLE
Converted HOWTO to markdown

### PR DESCRIPTION
**Pull request by Samathy**
Possible reason to close issue #93?

### CODE REVIEW

**Comment by bebehei** [comment]
I :heart: you. This had been work, I always wanted to avoid.

Let me take a look over it and merge it tonight.

**Comment by Jo-Con-El** [comment]
Could you please merge it and publish it on the web page?  At least that you will allow your new users like me something to read instead of going through raw XHTML. :-)

Later you can upgrade it to 1.4, but my point still stands.

Thanks!

**Comment by msimerson** [comment]
+1

How is this not merged? It makes rsnapshot feel "not maintained."

**Comment by sam-at-github** [comment]
@Jo-Con-El Will publish something on the web page shortly. @Samathy thanks. How did you generate this? Is it updated for rsnapshot version 1.4 or is it just a port of what was already there? Did you see the docbook source in the repo? Wondering whether we should maintain the docbook as the single source, or just get rid of that stuff and go with markdown as the single source. If we can generate markdown from the docbook automatically would prefer to go that router I think.

**Comment by msimerson** [comment]
Having worked with pandoc, and  converting from XHTML, XML, and mediawiki to Markdown, I'd recommend just dropping the docbook files and writing initially in GFM (GitHub Flavored Markdown) first. As a developer, you'll get **many** more PRs for docs authored first in Markdown.

**Comment by sam-at-github** [comment]
:+1:  for using Markdown as single source format and dropping the docbook. Note there are some minor formatting errors in this markdown. For reference http://rsnapshot.org/rsnapshot/docs/docbook/rest.html. The whole thing should be gone over and updated as mentioned.

For now I've added a link to existing HTML version on web page but @bebehei need to merge it into master.

**Comment by Samathy** [comment]
@sam-at-github This was made simply by running the file in docs/HOWTOS/rsnapshot-HOWTO.en.html though some html to markdown converter and fixing the errors. Nothing technical really.
It'll only be as up to date as that document.

I'm behind maintaining a single source, but agree with @msimerson that Markdown should be used instead of docbook. People will certainly be more willing to work on Markdown, which might make up for it maybe not being the /perfect/ format for the task.

**Comment by matkoniecz** [comment]
@maintainers

Can you consider rejecting this PR or merging it?

**Pull request closed without merging**
