### PR TITLE
Correct punctuation

### PR DESCRIPTION
**Pull request by hoclun-rigsep**

### CODE REVIEW

**Review by StefanMoch — APPROVED** [review]
okay

**Comment by DrHyde** [comment]
This needs to be applied to the docbook source, does it not, not to the HTML output?

**Comment by StefanMoch** [comment]
The text itself is contained in multiple files:
```
$ git grep -l 'contents of whatever it does into'
docs/HOWTOs/rsnapshot-HOWTO.en.html
docs/docbook/rsnapshot-HOWTO.en.fo
docs/docbook/rsnapshot-HOWTO.en.xhtml
docs/docbook/rsnapshot-HOWTO.en.xml
```

It seems like the html file is the canonical version as of v1.3.0, however: 319fafdbe162e4ad1a978287dad686fdaeeba149

```
From 319fafdbe162e4ad1a978287dad686fdaeeba149 Mon Sep 17 00:00:00 2001
From: drhyde <drhyde>
Date: Fri, 6 Oct 2006 14:32:01 +0000
Subject: [PATCH] Added HTML version of HOWTO to CVS.  This is the version
 we'll maintain for v1.3.0 onwards

---
 docs/HOWTOs/rsnapshot-HOWTO.en.html | 1596 +++++++++++++++++++++++++++
 1 file changed, 1596 insertions(+)
 create mode 100644 docs/HOWTOs/rsnapshot-HOWTO.en.html
```

All doc text changes after that commit have been made to this file. So, no: making the changes here seems right.

The docbook files have also been imported after that, but besides some cleanup, no text changes there:

- 66da0ff (import, first and last change to `docs/docbook/rsnapshot-HOWTO.en.xml`)
- c4b2531 (cleanup)
- a1a75f3 (cleanup)

The [Makefile](https://github.com/rsnapshot/rsnapshot/blob/master/docs/docbook/Makefile) also does _not_ handle the changed html file -- it has only rules for xhtml and others, not html.

I don't know. Maybe we should remove the docbook files altogether. We can always bring them back if needed.

**Comment by DrHyde** [comment]
Deleting the docbook monstrosity would DELIGHT me! So I'll merge this.

**Review by DrHyde — APPROVED** [review]

**Pull request merged**
