### PR TITLE
Cleanup repository

### PR DESCRIPTION
**Pull request by bebehei**
Branch which makes huge changes to the rsnapshot-repo. There is no actual code-change.

I deleted all auto-generated files, removed the cvs-id-tags, and removed stale files.

I added a CONTRIBUTING.md-file, added autoclean and autogen to generate/clean configure-script, etc. Credits to @myrdd @sam-at-github

*This change should get merged against 1.3.1, but to do this, it requires hard overwriting of master, where I want to get permission of @DrHyde or @djk20 *

### CODE REVIEW

**Comment by DrHyde** [comment]
Looks good. It won't auto-merge though - I guess that's because of me moving the repo to the organisation. But I'm happy for you to merge it manually.

**Comment by bebehei** [comment]
Nah, I can't merge automatically because my changes go against the commit of 1.3.1. I vote for resetting the current master-branch back to 1.3.1 and keep it as branch master-old.The That leads us to force a git push and update every fork, but it gives us the ability

**Comment by bebehei** [comment]
For Example, we don't have to merge commits, which introduce bugs like #51

**Comment by DrHyde** [comment]
On Wed, Feb 11, 2015 at 08:44:55AM -0800, Benedikt Heine wrote:

> Nah, I can't merge automatically because my changes go against the commit of 1.3.1. I vote for resetting the current master-branch back to 1.3.1 and keep it as branch master-old.The That leads us to force a git push and update every fork, but it gives us the ability

Ah, this is related to your post about doing a 1.3.1+bugfixes release?

I think the best thing to do would be to create a branch from the 1.3.1
tag and apply your changes to that, and then cherry-pick bugfixes from
master.

Most of your PR should apply cleanly to master though - there's only
about 20 lines of code changed, the rest is deleting or adding entire
files, so merge conflicts should be minimal.

-- 
David Cantrell | Godless Liberal Elitist

Disappointment:
  n: No results found for "priapic dwarf custard wrestling".

**Comment by sam-at-github** [comment]
:+1:. Changes merge fine into 1.3.1. I think what @DrHyde suggested is in line with what you were thinking @bebehei. To make it more concrete, the approach would be, or similar to:

    git clone https://github.com/rsnapshot/rsnapshot
    git branch -m master feature/future-master # rename current master.
    git checkout -b release-1.3.1 1.3.1 
    git branch dev # new branch for development and the cherry picking from future master.
    git branch master # reset master
    git checkout dev
    git remote add bebehei https://github.com/bebehei/rsnapshot
    git fetch bebehei
    git merge bebehei/feature/cleanup 
    git branch release-1.3.2 # Or do this later, once the list of critical bug fixes upstreams are most wanting is added.

Can you PR this?

Note we can delete release branch or tag and delete them. I'm kind of in favour of not deleting but don't care either way.

**Comment by bebehei** [comment]
@DrHyde That would go against the CONTRIBUTING-file I've written. My intention is to have one main branch (master), specific branches for the releases (release-*-*) and for every feature/bugfix a single branch. At the end of the day, we are able to merge bugfix-branches onto master and backport them to older versions with no effort.

I know, this makes some trouble, but I want to reset master to 1.3.1.

@sam-at-github Pls use release-branches only named release-<major>-<minor>, use the complete version (including the bugfix-number) only for tags.

**Comment by sam-at-github** [comment]
@bebehei I understand that you want minor release branches delete once merged into master. However, can we use `release-x.y.z` instead? I have done a PR on the contributing.md

**Comment by sam-at-github** [comment]
> I know, this makes some trouble, but I want to reset master to 1.3.1.

@bebehei this PR is against the wrong branch? Could you PR roughly what I have outlined above, then PR against the dev branch? You don't have to reset just rename the branch - as above.

**Comment by bebehei** [comment]
> @bebehei I understand that you want minor release branches delete once merged into master. However, can we use `release-x.y.z` instead? I have done a PR on the contributing.md

I roughly want to stick to http://semver.org (what the maintainers already stick to, without really aknowledging it). There you can distinguish, that you have to only bump the 3rd number, if you make only bugfixes. Otherwise you have to bump the 2nd or 1st number. A release-branch *MUST only* contain the 1st and the 2nd number in its name. I hope I can clarify, why to do this, later in this comment. If it is separated by a dash (e.g. `release-1-3`) or a dot (e.g. `release-1.4`), personally I don't really care about this.

>> I know, this makes some trouble, but I want to reset master to 1.3.1.

> @bebehei this PR is against the wrong branch? Could you PR roughly what I have outlined above, then PR against the dev branch? You don't have to reset master, just rename the branches - as above.

Now there is something unclear about a `dev`-branch and a `master`-branch. Just start clarify the word reset: For me, resetting is, if you move the branch pointer, that you have to push and force an update at your remote. If you do it the way in your script, we have
* master -> tag 1.3.1
* dev -> feature/cleanup.

So here we reset master to another position at the back and have to force push-updates later. I don't understand, where your script is different to the definition.

I would appreciate to go ahead, like the new CONTRIBUTING.md says: Create for every feature/bugfix a new branch and then either merge it to master, merge it into the specific release-branch too. This implies for me, that we reset master.

This has got a few good points for it: We know, what we will release. I don't want to pretend, that the devs don't know, what is merged into it, but the development of the last 6 years is only used by a small amount of people. Most of the users, still use version 1.3.1. So the new features in it, are untested. A review of these, could be quite helpful. If we organise it in a new way like it is described in CONTRIBUTING.md, we (especially myself) will get more overview, what is changed.

The way @DrHyde is slightly different. As I understand it, he wants me to branch out a release-branch `release-1-3` and cherry-pick the bugfixes. It is a possible way to go, but the repo stays different on master and 1.3.1. And we will have to care about 1.3.1 the next year(s). 

What should a release-branch do? As semver.org says, if you push the patch-version, there should only be new patches in it. So we have to assure, that we don't merge any new features into the according branch. So just create a new branch, call it `release-<major>-<minor>`, tag the release and you're almost finished. If new features get merged into master, they won't appear in your release. So if you merge bugfixes into master, you have to merge them to the according (everywhere, where the bug appears) release-branches, too. This makes backporting for distro-packages much easier.

If you experience a bug in your release, create a bugfix-branch, fix it and PR against master, then manually merge the branch to your release-branches. Tag the releases on the release-branches, push the tags and Travis will do the rest for you.

PS: Yeah, Travis is another thing. I've already written travis.yml and I'm experiencing about it. It makes releasing and testing a lot easier.

**Comment by bebehei** [comment]
You're right. I'll rebase my branch onto the real master and not on tag v1.3.1

**Pull request merged**
