### PR TITLE
Doc tidy / reformat.

### PR DESCRIPTION
**Pull request by sam-at-github**
Minors formatting changes to make things markdown and github compatible. Good to get this done for 1.4.

### CODE REVIEW

**Comment by bebehei** [comment]
changes in CONTRIBUTING.md rejected. I would like to use dashes in branches and dots in tags. Why do you always want to subversively change this? you did it in bebehei/rsnapshot#3, too.

**Comment by sam-at-github** [comment]
Oops I thought you said you didn't care. I think dots is more standard. Up to you though. I will change back to "-". Two secs.

**Comment by bebehei** [comment]
Could you tell me, why you use in your markdown: (mind the space at the beginning)

     # heading

instead of

    # heading

There is no need to correct this. I've never seen this. I'm just curious, why you did it.

**Comment by bebehei** [comment]
Sorry, this has been an invalid. I've been reading the github-diff wrong.

**Pull request closed without merging**
