### PR TITLE
Test cleanup

### PR DESCRIPTION
**Pull request by kevinlyles**
This is the reworked first portion of [pull request 36](https://github.com/rsnapshot/rsnapshot/pull/36), and just cleans up the test code a bit.  It does have the effect of actually testing a few more things, since we now (correctly) look at exit status instead of output.

### CODE REVIEW

**Comment by bebehei** [comment]
Thanks, for me this looks well. Maybe @sam-at-github can have a look over this.

**Comment by sam-at-github** [comment]
Mostly looks good. I don't like SysWrap.pm. Unnecessary complication. I would suggest removing for this commit. Maybe add it in a separate PR with a clear rationale for using it. I.e. I'm ok with everything but 
db78650, and  df9bba3.

**Comment by sam-at-github** [comment]
Actually yeah we should probably use this wrapper or something similar. But at the same time we do that do xUnit - http://search.cpan.org/~ether/Test-Class-0.48/lib/Test/Class.pm.

**Comment by bebehei** [comment]
IMO such a wrapper is a thing, what adds complexity but on the other hand we have a tool, which gives us ease to administrate tests (e.g. when the "compiled" rsnapshot-executable path changes, we have to change all tests. I like it too.

**Comment by sam-at-github** [comment]
Argh,  we can't use Test::Class is no go since its not core(?). Test::Unit is also non core. AFAIK there is no xUnit module in core. FYI I'm not pursuing this anymore.

**Comment by bebehei** [comment]
I wouldn't mind if we have some extra deps for testing only.

Pursuing in what? Unit tests or the testsuite in general?

**Comment by sam-at-github** [comment]
Yeah just Test::Class (I think) for tests. However we'd have to make sure you could build and install without testing. Something to consider is when you build a cpan module it runs the tests (I think, been a while).
> Pursuing in what? Unit tests or the testsuite in general?
Pursuing testsuite in general right now.

**Comment by bebehei** [comment]
> Pursuing testsuite in general right now.

N2K

**Pull request merged**
