### PR TITLE
wait between rsync tries

### PR DESCRIPTION
**Pull request by dani9**
Hi team,

I’ve implemented a delay between the rsync tires. 

This is my first contribution to this project, and I would appreciate any feedback or suggestions for further improvements.
Let me know if you need any more adjustments!

### CODE REVIEW

**Comment by DrHyde** [comment]
Looks good to me!

**Comment by sgpinkus** [comment]
Seems to work. Only thing I noticed is the new option will accept a non numerical string value and seems to treat it as zero. Where as the existing `rsync_numtries` rejects non numerical values. Maybe could just copy the same parsing logic

**Comment by dani9** [comment]
i have implemented that only integer values are allowed.

should i squash my commits into a single one?

**Comment by sgpinkus** [comment]
If you don't squash, we'll squash on merge so either or.

**Review by sgpinkus — APPROVED** [review]
Looks good to me.

**Comment by sgpinkus** [comment]
> I have found some local path in two test configuration files. I replaced them with variables in my last commit.

Oh you did too. Tests still passed!

> ...man page

It's generated from perldoc at the bottom of the rsnapshot script.

**Comment by dani9** [comment]
I have added the perldoc entry. I think everything is done now.

**Review by sgpinkus — APPROVED** [review]

**Comment by sgpinkus** [comment]
Looks good. Will merge in a few days if no one else comments or does it before me :).

**Comment by sgpinkus** [comment]
Merged. Thanks!

**Pull request merged**
