### PR TITLE
Exactly "perltidy -b -nola -noll -tabs -l 80 -io `find -name "*.pl"".`

### PR DESCRIPTION
**Pull request by sam-at-github**
Just tidy the code. Mainly effects rsnapshot-program.pl. Did not do anything manually to keep it predictable and automated. perltidy command achieves roughly the existing conventions in the code.

This another thing I wanted to get done sooner rather than later. Probably actually best for @bebehei, or someone to do just before releasing 1.4. However would be good if you could leave this ticket open for discussion / reminder. I can push it again or later if need be.

### CODE REVIEW

**Comment by bebehei** [comment]
Thanks, I also wanted to ask you for this. Are there only 160 lines changed in `rsnapshot-program.pl`? I thought the indentation was much uglier.

**Comment by bebehei** [comment]
Ok, github didn't show me the changes in `rsnapshot-program.pl`. Sry, i've accidentally looked at `rsnapshot-diff.pl`

**Comment by bebehei** [comment]
I've gone partially over the diff. We have to do make the change in multiple commits.

**Comment by sam-at-github** [comment]
Why? This should be done as the very last thing for 1.4 release.

**Comment by bebehei** [comment]
closing, new PR is at #85

**Pull request closed without merging**
