### PR TITLE
add additional filetest -d for config-file; fixes #51

### LINKED ISSUE #51: If config-file is a folder, config_version is not found!
bebe@butter > ls
    bin  files  rsnapshot  rsnapshot.conf  rsnapshot.log  testcase
    bebe@butter > rsnapshot -c rsnapshot daily
    Config file "rsnapshot" does not exist or is not readable.
    bebe@butter > ./rsnapshot/bin/rsnapshot -c rsnapshot daily
    ----------------------------------------------------------------------------
    rsnapshot encountered an error! The program was invoked with these options:
    ./rsnapshot/bin/rsnapshot -c rsnapshot daily
    ----------------------------------------------------------------------------
    ERROR: config_version was not defined. rsnapshot can not continue.
    bebe@butter >

rsnapshot is (1.3.1-5 Archlinux, roughly 1.3.1), ./rsnapshot/bin/rsnapshot is built from the current master.

Probably the commit 051d5b5a introduced it. I haven't tested this yet.

### PR DESCRIPTION
**Pull request by bebehei**

### CODE REVIEW

**Comment by bebehei** [comment]
Note to myself, tests are missing again.

**Comment by sam-at-github** [comment]
:+1: Maybe a little verbose detecting why reading config failed.

**Comment by sam-at-github** [comment]
Merged it.

**Comment by bebehei** [comment]
Tests are still missing ;-)

I will create another PR for it.

**Pull request merged**
