### PR TITLE
fix rsnapshot failing to parse per-backup additional short args

### LINKED ISSUE #215: Error when adding rsync_short_args to a backup
Hi,

I use Debian Stretch 9.5 with rsnapshot version 1.4.2-1. I have trouble setting a specific short argument for rsync for a backup:
```
backup  root@web.lxc:/    web.lxc/    +rsync_short_args=-x
```
This is the output:
```
root@marco# rsnapshot -vc rsnapshot-test.conf daily
echo 22003 > /var/run/rsnapshot.pid 
mv /data/backup/themis/daily.2/ /data/backup/themis/daily.3/ 
mv /data/backup/themis/daily.1/ /data/backup/themis/daily.2/ 
/bin/cp -al /data/backup/themis/daily.0 /data/backup/themis/daily.1 
/usr/bin/rsync -a -x --delete --numeric-ids --relative --delete-excluded \
    --exclude=/proc/ --exclude=/sys/ --exclude=/dev/ --exclude=/run/ \
    --rsh=/usr/bin/ssh root@web.lxc:/ /data/backup/themis/daily.0/web.lxc/ 
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot -vc rsnapshot-test.conf daily 
----------------------------------------------------------------------------
ERROR: /usr/bin/rsync returned 1 while processing root@web.lxc:/
touch /data/backup/themis/daily.0/ 
rm -f /var/run/rsnapshot.pid
```
If I execute the printed rsync command manually everything works fine. So subsequently I traced the process, which revealed this:
```
execve("/usr/bin/rsync", ["/usr/bin/rsync", "-a -x", "--delete", "--numeric-ids", ...
...
write(2, "rsync: -a -x: unknown option", 28) = 28
```
Apparently rsnapshot uses "-a -x" as a single option for rsync, which results in an error. If I remove the dash before the `x`, it's not valid anymore:
```
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot -vc rsnapshot-test.conf daily 
----------------------------------------------------------------------------
ERROR: rsync_short_args "x" not in correct format
ERROR: rsnapshot-test.conf on line 51:
ERROR: backup root@web.lxc:/ web.lxc/ +rsync_short_args=x - Syntax error on \
         line 51 in extra opts: +rsync_short_args=x 
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in rsnapshot-test.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
```
Is this a bug or can I solve this problem in a different way?

Cheers,
Marco

### PR DESCRIPTION
**Pull request by Yannik**
fixes #215

### CODE REVIEW

**Comment by sam-at-github** [comment]
Agreed this is a bug. But can you possibly add a test that shows the previous failure mode to this PR?

**Comment by bebehei** [comment]
@Yannik Please have a look in #191, too.

And out of curiosity: Are you susbscribed to `debian-users-german` by accident?

**Comment by Yannik** [comment]
@bebehei No, I've never been subscribed to that list. Perhaps you know my name from the lkml, or some other mailinglist?

About #191: Unfortunately I do not have the necessary time to take over maintenance of rsnapshot. :(

@sam-at-github I'll see if I find the time to take care of that.

**Comment by Yannik** [comment]
@sam-at-github Unfortunately I do not have the time to look into the specifics of rsnapshot for creating a test for this. Perhaps you can go ahead and do this. Otherwise it can perhaps be merged w/o a test.

**Comment by sam-at-github** [comment]
Oh this fixed in master by #156, tests added in #157. Hopefully we can version bump soon.

**Pull request closed without merging**
