### PR TITLE
Add support for skipping _delete.$$ directory deletions

### PR DESCRIPTION
**Pull request by guestisp**
Add support for skipping _delete.$$ directory deletions during the backup/rotation phase.

On huge servers, this could speed up the whole process a lot, in our test, about 4 hours less then before.

Set use_lazy_deletes to 2 to use this feature

### CODE REVIEW

**Comment by guestisp** [comment]
This is a sample for a script deleting all `_delete.$$` directories, must be changed according each rsnapshot installation. In mine config I have 1 `snapshot_root` for each host, thus the following is working fine:

 for i in $(find /var/backups/rsnapshot/ -maxdepth 2 -type d -regex '.*/_delete\.[0-9]+$'); do mkdir /tmp/empty.$$; rsync -a --delete /tmp/empty.$$/ ${i}/; rmdir /tmp/empty.$$; rmdir ${i}; done

"rsync" syncing an empty directory (resulting in deleting all files) in much faster than "rm". In my environment, I'm able to delete in about 48 minutus the same data that "rm" deletes in 4 hours. There are a lot of docs on net explaining why rsync is much faster doing this

**Comment by guestisp** [comment]
Any news on this?

**Comment by guestisp** [comment]
bump

**Comment by guestisp** [comment]
Any comment ?

**Comment by sam-at-github** [comment]
Why don't you just set you last rotation level to have a really high value?

    daily 7
    weekly 4
    monthly 10000

**Comment by guestisp** [comment]
This could be an idea. I have to test.

**Comment by MTecknology** [comment]
@guestisp Is there any chance you could follow up on your testing? Is this still PR still something you think should be included in rsnapshot? If so, would you also consider adding some test cases to prevent regressions?

**Comment by guestisp** [comment]
@MTecknology I'm sorry but i'm not using rsnapshot anymore. I've moved to BackupPC v4

**Comment by ebogaard** [comment]
Iḿ using this PR for months now. Works great and is a great addition to reduce the time to back-up, as you can separately delete the old files on a time you choose (separate from any other back-ups running).

**Comment by sgpinkus** [comment]
Don't think there is a strong case for this, as an alternative over very large last retain number as shown above. Closing.

**Pull request closed without merging**
