### PR TITLE
grab output from rsync and put to log

### PR DESCRIPTION
**Pull request by bebehei**
This snippet allows you to log the entries of rsync and pipe them into the rsnapshot logfile.

### CODE REVIEW

**Comment by bebehei** [comment]
On rsnapshot-maintainers David Keegel stated:

> I have some concerns about that PR.  If I am reading it right, the
> patched version would ask a shell to interpret the commands to be
> run.  I deliberately changed the way rsync was invoked so it would
> use an array with no need for shell interpreting, with the aim of
> supporting things like directory names with spaces in them.  That
> seems to be the opposite.
> 
> I think one thing which was missing with this approach was getting
> print_cmd to quote things like spaces that appear within array
> elements, so that people can copy & paste the output of print_cmd
> into a shell and have it do what rsnapshot would do (and also so
> log readers can distinguish between literal spaces and spaces to
> separate arguments).
> 
> I guess another missing thing was a comment to explain something
> about this around the "system(@cmd_stack);" call.

**Comment by bebehei** [comment]
As far as I can see, a shell is only spawned if there is no shell-meta-character in the @cmd_stack-array.
What is the problem in general spawning an extra-shell?

**Comment by bebehei** [comment]
I did some tests under perl 5.20.0 and it appears, just that the call of open is important.

    #!/usr/bin/perl
    
    # hello is a hello-world-program with no functionality
    # the arguments are just bogus and ignored by hello
    # some arguments may cause perl to behave other way
    #my @array=('./hello', '-rf', ">/tmp/test.txt");
    #my @array=('./hello', '-rf', '"/tmp/rsnapshot-git/"', ">/tmp/test.txt");
    my @array=('./hello', '-rf', '"/tmp/rsnapshot-git/"');
    #my @array=('./hello', '-rf', '/tmp/rsnapshot-git/');
    
    #does not open a shell
    print "system\n";
    system(@array);
    
    #opens a shell
    print "open\n";
    open(FH, "@array 2>&1 |");
    while(<FH>){
    	print $_;
    }
    
    #does not open a shell
    print "open advanced\n";
    open(FH, "-|",  (@array, "2>&1 |") );
    while(<FH>){
    	print $_;
    }

**Comment by djk20** [comment]
Benedikt,

The problem IIUC is if a directory/file name (eg: backup root, source,
destination, exclude, ...) includes characters like space " ".

If you join up all the args (separated by space), then how is the shell
supposed to distinguish between
* space to separate arguments
* space which happens to be part of a directory/file name (eg "My
Documents").

Try some tests where some elements of @array have spaces in them.

Or try running "make test" test in the rsnapshot repo before & after
changing system().
I would expect t/snapshot_root_with_space.t to fail after system() is
changed.


On 20 January 2015 at 15:55, Benedikt Heine <notifications@github.com>
wrote:

> As far as I can see, a shell is only spawned if there is no
> shell-meta-character in the @cmd_stack-array.
> What is the problem in general spawning an extra-shell?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/DrHyde/rsnapshot/pull/46#issuecomment-70604626>.
>



-- 

David Keegel <david.keegel@gmail.com>

**Comment by bebehei** [comment]
Ok, sorry for the inconvenience. I use now IPC::open3 to grab the output.

Thanks for reminding me, that there are available tests, too. I've run them now with the latest commit and it passed with 7/7. Of course I have to test it right, especially in terms of output-handling with rsync.

PS: My previous commit fixed it kind of, but there had been other problems.

**Comment by bebehei** [comment]
Ok, I finished it now. Make test does PASS with all 6(!, yeah, so many!) tests!

In terms of time-regardance of the rsync-output, it is flushed and IMO this can get merged.

Of course before merging this branch should get rebased!

**Pull request closed without merging**
