### PR TITLE
Fix/tests

### PR DESCRIPTION
**Pull request by sam-at-github**
Some tidy up of tests. Refs #60. As mentioned there, likely we will change test setup in future but for now good to have tests that work. This commit merges and closes #30, #31, #62, fixes an issues with gnu_cp.t.

### CODE REVIEW

**Comment by bebehei** [comment]
Tests are building well on travis-CI. SSH-test wants to connect to localhost. The build hang because it asked for User-input, I stopped it now.

**Comment by sam-at-github** [comment]
Yep thx. Working on fix now.

**Comment by sam-at-github** [comment]
Ok that did not work. Now SSH wants a password. I'll have a look at setting an sshd config via travis conf. Otherwise may have to just skip the test on Travis.

**Comment by bebehei** [comment]
`CI=true` does the trick at http://docs.travis-ci.com/user/ci-environment/#Perl-VM-images

**Comment by sam-at-github** [comment]
I'm happy with this now. Merge?

**Comment by bebehei** [comment]
Let me look over it.

**Pull request merged**
